x-common: &common
  restart: unless-stopped
  tmpfs:
    - /var/tmp
    - /run:exec
  shm_size: 1gb
  read_only: false
  environment: &common-env
    DISPLAY: ':0'
    PULSE_SERVER: 'unix:/run/pulse/native'
    RETROSTACK_IDLE_TIMEOUT: '600'
    RETROSTACK_FRONTEND_MODE: 'standalone'
  labels:
    io.balena.features.kernel-modules: '1'
    io.balena.features.firmware: '1'
    io.balena.features.dbus: '1'
  volumes:
    - retrostack-emulator-control:/run/retrostack-emulators
    - retrostack-shared:/run/retrostack-shared:ro
    - emulationstation-config:/config
    - emulationstation-roms:/roms:ro
    - emulationstation-bios:/bios:ro
    - x11-unix:/tmp/.X11-unix:ro
    - pulse-socket:/run/pulse:ro
  devices:
    - /dev/dri:/dev/dri
    - /dev/input:/dev/input
    - /dev/snd:/dev/snd

services:
  retroarch:
    <<: *common
    profiles: [retroarch, all]
    build:
      context: .
      target: retroarch
    image: docker.io/blackoutsecure/retrostack:retroarch
    container_name: retrostack-retroarch

  ppsspp:
    <<: *common
    profiles: [ppsspp, all]
    build:
      context: .
      target: ppsspp
    image: docker.io/blackoutsecure/retrostack:ppsspp
    container_name: retrostack-ppsspp

  dolphin-emu:
    <<: *common
    profiles: [dolphin, all]
    build:
      context: .
      target: dolphin-emu
    image: docker.io/blackoutsecure/retrostack:dolphin-emu
    container_name: retrostack-dolphin-emu

volumes:
  emulationstation-config:
  emulationstation-roms:
  emulationstation-bios:
  retrostack-emulator-control:
  retrostack-shared:
  x11-unix:
  pulse-socket:
